name: "Bump NPL CLI version"

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      CLI_VERSION:
        description: "NPL CLI version to bump to"
        required: false

env:
  CI_PIPELINE_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  SLACK_WEBHOOK: "${{ secrets.SLACK_URL }}"
  SLACK_USERNAME: "bumperBot"
  SLACK_ICON: "https://avatars.githubusercontent.com/u/56019787?s=50&v=4"
  SLACK_CHANNEL: "#platform-status"
  SLACK_TITLE: " "
  SLACK_FOOTER: "homebrew-tools#bump-cli-version.yml"
  MSG_MINIMAL: true

jobs:
  bump_verify:
    name: "Bump NPL CLI version in formula"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set Git user"
        run: |
          git config --global user.name "noumenadigital-bot"
          git config --global user.email "noumenadigital-bot@users.noreply.github.com"

      - name: "Determine CLI version"
        id: resolve-version
        run: |
          if [ -z "${{ inputs.CLI_VERSION }}" ]; then
            version=$(curl -s https://api.github.com/repos/NoumenaDigital/npl-cli/releases/latest | jq -r .tag_name)
          else
            version="${{ inputs.CLI_VERSION }}"
          fi
          echo "Resolved version: $version"
          echo "CLI_VERSION=$version" >> $GITHUB_ENV
          echo "PLATFORM_VERSION_TAG_LINK=https://github.com/NoumenaDigital/npl-cli/releases/tag/$version" >> $GITHUB_ENV

      - name: "Install Homebrew"
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
          echo "/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: "Download binaries and calculate checksums"
        run: |
          declare -A archs=(
            [macos_aarch64]="npl-cli-macos-aarch64-${CLI_VERSION}"
            [macos_x86_64]="npl-cli-macos-x86_64-${CLI_VERSION}"
            [linux_aarch64]="npl-cli-linux-aarch64-${CLI_VERSION}"
            [linux_x86_64]="npl-cli-linux-x86_64-${CLI_VERSION}"
          )
          for arch in "${!archs[@]}"; do
            url="https://github.com/NoumenaDigital/npl-cli/releases/download/${CLI_VERSION}/${archs[$arch]}"
            echo "Downloading $url"
            curl -L -o "$arch" "$url"
            sha256=$(shasum -a 256 "$arch" | awk '{print $1}')
            echo "${arch}_SHA256=$sha256" >> $GITHUB_ENV
          done

      - name: "Ensure formula file is present"
        run: |
          if [ ! -f npl.rb ]; then
            echo "Downloading npl.rb from master"
            curl -O https://raw.githubusercontent.com/NoumenaDigital/homebrew-tools/master/npl.rb
          fi

      - name: "Update formula file"
        run: |
          sed -i -e "s/^  version \".*\"/  version \"${CLI_VERSION}\"/" npl.rb

          sed -i -e "/url .*macos-aarch64/!b;n;s/sha256 \".*\"/sha256 \"${macos_aarch64_SHA256}\"/" npl.rb
          sed -i -e "/url .*macos-x86_64/!b;n;s/sha256 \".*\"/sha256 \"${macos_x86_64_SHA256}\"/" npl.rb
          sed -i -e "/url .*linux-aarch64/!b;n;s/sha256 \".*\"/sha256 \"${linux_aarch64_SHA256}\"/" npl.rb
          sed -i -e "/url .*linux-x86_64/!b;n;s/sha256 \".*\"/sha256 \"${linux_x86_64_SHA256}\"/" npl.rb

      - name: "Build and install formula"
        run: |
          brew install --build-from-source ./npl.rb

      - name: "Run formula test block"
        run: |
          brew test --verbose ./npl.rb

#      - uses: tibdex/github-app-token@v2.1.0
#        id: generate-token-pr
#        with:
#          app_id: ${{ secrets.GH_ND_TOKEN_PR_APP_ID }}
#          private_key: ${{ secrets.GH_ND_TOKEN_PR_APP_PRIVATE_KEY }}

      - name: "Create pull request"
        uses: peter-evans/create-pull-request@v6
        id: cpr
        with:
          title: "Bump NPL CLI version to ${{ env.CLI_VERSION }}"
          commit-message: "Updated NPL CLI version to ${{ env.CLI_VERSION }}"
          branch: "Bump-cli-${{ env.CLI_VERSION }}"
          base: "master"
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}

#      - name: "Report action required"
#        if: ${{ steps.cpr.outputs.pull-request-operation == 'created' }}
#        uses: rtCamp/action-slack-notify@v2
#        env:
#          SLACK_TITLE: "Action required"
#          SLACK_MESSAGE: "Please merge <${{ steps.cpr.outputs.pull-request-url }}|homebrew-tools PR #${{ steps.cpr.outputs.pull-request-number }}> to bump the NPL CLI version to <${{ env.PLATFORM_VERSION_TAG_LINK }}|${{ env.CLI_VERSION }}>."
#          SLACK_COLOR: "660033"
#
#      - name: "Report failure"
#        if: ${{ failure() }}
#        uses: rtCamp/action-slack-notify@v2
#        env:
#          SLACK_MESSAGE: "The <${{ env.CI_PIPELINE_URL }}|homebrew test> failed for NPL CLI release <${{ env.PLATFORM_VERSION_TAG_LINK }}|${{ env.CLI_VERSION }}>."
#          SLACK_COLOR: ${{ job.status }}
